#ifndef DYNAMIXEL_CONTROLS
#define DYNAMIXEL_CONTROLS

#define DYNAMIXEL_XL430 // TODO: move to board file
#ifdef DYNAMIXEL_XL430
// https://emanual.robotis.com/docs/en/dxl/x/xl430-w250/#control-table-of-eeprom-area


#define DYNAMIXEL_CTRL_TABLE_EEPROM_START_ADDR 0
#define DYNAMIXEL_CTRL_TABLE_EEPROM_LENGTH 61

#define DYNAMIXEL_CTRL_TABLE_RAM_START_ADDR 64
#define DYNAMIXEL_CTRL_TABLE_RAM_LENGTH 83

// EEPROM Fields
#define DYNAMIXEL_CTRL_TABLE_MODEL_NUM_ADDR 0 
#define DYNAMIXEL_CTRL_TABLE_MODEL_INFO_ADDR 2
#define DYNAMIXEL_CTRL_TABLE_FIRMWARE_VERSION_ADDR 6
#define DYNAMIXEL_CTRL_TABLE_ID_ADDR 7
#define DYNAMIXEL_CTRL_TABLE_BAUD_RATE_ADDR 8
#define DYNAMIXEL_CTRL_TABLE_DRIVE_MODE_ADDR 10
#define DYNAMIXEL_CTRL_TABLE_OPERATE_MODE_ADDR 12
#define DYNAMIXEL_CTRL_TABLE_STARTUP_CONFIG_ADDR 60

// RAM fields
#define DYNAMIXEL_CTRL_TABLE_TORQUE_ENABLE_ADDR 64
#define DYNAMIXEL_CTRL_TABLE_LED_ADDR 65
#define DYNAMIXEL_CTRL_TABLE_STATUS_RETURN_LEVEL_ADDR 68
#define DYNAMIXEL_CTRL_TABLE_REGISTERED_INSTRUCTION_ADDR 69
#define DYNAMIXEL_CTRL_TABLE_HARDWARE_ERROR_STATUS_ADDR 70
#define DYNAMIXEL_CTRL_TABLE_VELOCITY_I_GAIN_ADDR 76
#define DYNAMIXEL_CTRL_TABLE_VELOCITY_P_GAIN_ADDR 78
#define DYNAMIXEL_CTRL_TABLE_POSITION_D_GAIN_ADDR 80
#define DYNAMIXEL_CTRL_TABLE_POSITION_I_GAIN_ADDR 82
#define DYNAMIXEL_CTRL_TABLE_POSITION_P_GAIN_ADDR 84
#define DYNAMIXEL_CTRL_TABLE_PRESENT_VELOCITY_ADDR 128
#define DYNAMIXEL_CTRL_TABLE_PRESENT_POSITION_ADDR 132

#else
#error Need to define dynamixel servo (XL430, ...)
#endif

#endif